%% get all words from the book  -- !! select the book first !! --

book = 'JP'; % US for the "On cooking" book

if strcmp(book,'JP')
    filename = 'cookbook_japanese.txt';
elseif strcmp(book, 'IT')
    filename = 'cookbook_italian.txt';
else
    filename = 'on_cooking_book_2014.txt';
end

str = extractFileText(filename); % this function doesn't recognize if a word was split by paragraph, as: pre-
% paration --> these become 2 tokens "pre-" and "paration", so, some verbs may have been missed
textData = split(str,newline);
documents = tokenizedDocument(textData);
documents = addPartOfSpeechDetails(documents);
tdetails = tokenDetails(documents);


%% get only the verbs

verbs = tdetails(tdetails.PartOfSpeech=='verb',:);
verbs_token = verbs.Token';
verbs_token_lemma = normalizeWords(verbs_token,'Style','lemma');

bag = bagOfWords(verbs_token_lemma);

[bag,idx] = removeEmptyDocuments(bag);
bag = removeShortWords(bag,2); % with 2 or less
bag = removeLongWords(bag,15); % with 15 or more
bag = removeInfrequentWords(bag,5);


%% get only movement-related verbs

exclude_not_actions= ["accept","add","admit","advertise","advise","afford",...
    "approve","authorize","avoid","borrow","build","buy","calculate","call",...
    "cancel","change","charge","check","choose","complain","complete","confirm",...
    "consider","convince","count","decide","decrease","deliver","develop",...
    "dismiss","dispatch","distribute","divide","drop","employ","encourage",...
    "establish","estimate","exchange","extend","fall","fix","fund","get",...
    "worse","improve","increase","inform","install","invest","invoice","join",...
    "lend","lengthen","lower","maintain","manage","measure","mention","obtain",...
    "order","organise","owe","own","pack","participate","pay","plan","present",...
    "prevent","process","produce","promise","promote","provide","purchase",...
    "raise","reach","receive","recruit","reduce","refuse","reject","remind",...
    "remove","reply","resign","respond","return","rise","sell","send","seek",...
    "separate","shorten","split","structure","succeed","suggest","write",...
    "publish","reserve","print","select","make","vary","use","ask","meet",...
    "teach","understand","base","come","pass","enter","stay","learn","want",...
    "see","happen","watch","taste","swish","bury","know","feel","have",...
    "prove","celebrate","bear","eat","look","chew","sip","care","imitate",...
    "suck","drink","enjoy","mean","stop","polish","plain","clench",...
    "surround","heap","azuhi","steep","enclose","drench","sprig",...
    "invite","convert","donabe","coohing","enrich","alternate",...
    "lidded","test","insulate","elevate","half","replenish","uncover",...
    "trirnmed","devein","twirl","dominate","impress","concentrate","temper",...
    "conduct","bind","counteract","stffing","ball","wing","hing","flush",...
    "sautded","define","heavy-bottomed","tilt","take","let","tuck","wish",...
    "omit","shed"];

exclude_process = ["fry","pan-fry","grill","bake","roast","melt",...
    "freeze","thaw","coagulate","simmer","poach","boil","brown","broil",...
    "braise","chill","blanch","stew","crisp","emulsify","foam","evaporate"...
    "thicken","dry","smoke","hold","marinate","refrigerate","preheat",...
    "reheat","dissolve","toast","pan-roasted","dilute","unbleached","cool",...
    "soften","sauté","heat","absorb","warm","puree","macerate","incorporate",...
    "bruise","steam","deep-fry","pickle","parboil","vinegared","burn",...
    "brew","ferment","overcook","freeze-dry","pan-broil","saturate",...
    "sautéing","caramelize","cure","tenderize","deglaze","pasteurize",...
    "sear","degrease","curdle","breed","stir-fry","distill","microwave",...
    "condense","pan-fried","precook","uncooked","stir-frying","granulate",...
    "foil-cooked","steam-simmered","deepfrying"];

exclude_purposes = ["add","cook","prepare","cut","remove","serve","transfer","garnish","store",...
    "sanitize","open","close","compose","spread","discard","combine","clean","shape","split",...
    "extract","eliminate","assemble","cover","baste","empty","wash","flatten", "scramble"];

% NOTE: baste = pour juices or melted fat over (meat) during cooking in
% order to keep it moist --> the action is to pour, already catched.

% Scrambled eggs are eggs whisked with seasonings and then sautéed. They are 
% stirred nearly constantly during cooking. --> it is a cooking process

exclude_others = ["touch","expose","curl","catch","pack","push",...
    "pull","press","hone","shred-cut"];

% note: hone is excluded because it is done to a tool as it degrades - it
% is a deffect of the tool itself, not related to handling food or its
% containers, etc.

exclude_errors = ["swirl","scorch","glaze","julienne","churn","red","color",...
    "ebi","short-grain","fluff","shallow","knob","whisk","dtied","ball","cod",...
    "sauce","long-grain","sweet","pipe","jiggle","dub","force-cool","yolk",...
    "green","flour","wooden","sink","creen","mahe","shiso","saucepan","turnip",...
    "egg","pan","spoon","mixture","bubble","oil","low","tsp","half",...
    "rim","lemon","earthenware","ffi","serzte","char","slash"];

% SYNONYMS:
% crack = mill, grind
% plunge/dip
% drain/strain


exclude_more = ["emit","liquid","scald","tbsp","disturb","cooh","serae","ladle","seroe",...
    "line","halve","off","swim","decorative","reconstitute","ounce",...
    "salt-grilled","till","control","crosswise","determine","wait","dredge",...
    "save","force","destroy","towel","white-fleshed","slide","cup","bone",...
    "thin-sliced","sharpen","ensure","bevel","judge","support","scale",...
    "dampen","face","scatter","appeal","consume","mature","scoop","pat",...
    "ripen","round","handle","move","desire","attach","coat","proceed",...
    "medium","textured","bite-sized","dust","wheat","improvise","bamboo",...
    "tie","knead","slip","yield","moisten","pound","string","loose",...
    "settle","firm","fit","inch","rest","soy","result","label","freshen",...
    "flavor","create","deepfried","slit","name","invent","allow","flake",...
    "require","regard","involve","harmonize","draw","pink","list","refer",...
    "seed","medium-sized","top","prefer","tint","act","sweeten","slot",...
    "enhance","retain","appear","represent","recommend","dress","limit",...
    "accompany","tend","attempt","direct","stick","finish","replace","pare",...
    "wrrh","bottle","note","discuss","stock","can","substitute","seaweed",...
    "tear","wring","powder","square","size","raw","associate","originate",...
    "soak","describe","read","think","remain","sit","pull","lose","leave",...
    "compare","try","start","arrange","savor","discover","continue",...
    "depend","carrot","float","set","devise","adjust","import","accord",...
    "remember","form","adapt","achieve","visit","cultivate","expand",...
    "apply","like","suit","include","lack","mask","contain","appreciate",...
    "grasp","stand","tell","run","lift","bring","play","put","recognize",...
    "preserve","release","introduce","design","stalk","indicate","display",...
    "hang","sesame","salt","refine","skewer","recipe","complement","take",...
    "let","treat","lie","soup","give","worry","show","need","work","say",...
    "expect","keep","seem","help","package","find","so-called","grow",...
    "repeat","become","believe","begin","end","refresh","offer",...
    "follow","live","spend","diminish","precede","homemade","lead",...
    "accommodate","speak","stu","fasten","protrude","connect","master",...
    "sautéed","execute","constitute","contribute","avored","blacken",...
    "prize","match","nished","attened","oven","season","collect","strip",...
    "ripe","assort","taper","characterize","last","acquire","tting","mix",...
    "undergo","consist","elongate","unsmoked","protect","pasta","supply",...
    "dough","recall","travel","embed","throw","resemble","mottle","point",...
    "satisfy","specialize","rosemary","lling","eshed","detach","dig",...
    "permit","crowd","layer","stack","shrink","tip","amalgamate","double",...
    "pale","thin","teaspoon","tablespoon","wilt","tted","loosen","enamel",...
    "brie","beneath","carve","attening","subside","lengthwise","arge",...
    "snap","artichoke","tomato","overlap","cling","light","drizzle",...
    "atten","sizzle","transform","smear","blemish","lled","lamb","prod",...
    "discolor","smother","purée","unshelled","retrieve","correct","box",...
    "dunk","dozen","ltered","gather","dot","edge","ridge","lay","hop",...
    "spatula","tender","slap","pile","broad","envelop","hollow","omemade",...
    "hand-rolled","drive","level","lasagne","near","puncture","cause",...
    "white","potato","sac","truss","sever","veal","crisp-fried","saute",...
    "gash","sparkle","illus","accomplish","account","accumulate","activate",...
    "address","adopt","aerate","affect","age","aid","air-dry","all-purpose",...
    "alter","analyze","aquafarmed","argue","arrive","assign","assist",...
    "balance","barbecue","barde","batter","below","benefit","beurre","bleach",...
    "bond","brine","buckwheat","burst","butcher","butter","butterfly","cake",...
    "calf","calibrate","candy","castrate","cater","certify","chafe",...
    "cheddar","chef","chicken","chiffonade","chocolate","circulate",...
    "claim","clarify","class","classic","classify","cocoa","collapse",...
    "compensate","complicate","compound","compress","confuse","construct",...
    "consult","contact","contaminate","contrast","corn","cornstarch",...
    "cost","crack","cream","creamy","credit","crust","crystallize","cube",...
    "culture","curve","damage","darken","decline","decorate","dedicate",...
    "deep","deflate","demand","demonstrate","dent","derive","designate",...
    "dessert","detect","deteriorate","devote","die","differ","digest",...
    "dill","dine","diner","disperse","distinguish","dock","domesticate",...
    "dorling","double-acting","drape","drip","dry-aged","duck","emphasize",...
    "encase","encounter","escape","evaluate","evolve","exceed","exist",...
    "experience","experiment","explain","express","extrude","fabricate",...
    "facilitate","fail","farm","fat","feature","fee","feed","figure",...
    "filter","fish","flame","flourish","flow","flute","focus","formula-fed",...
    "formulate","fortify","french","frost","fructose","fruit","full-flavored",...
    "fur","gain","gel","gelatinize","generate","glucose","gluten","goat",...
    "grade","grain","grip","group","hard-boiled","hard-cooked","harden",...
    "harvest","heart-shaped","herring","hide","hull","hydrogenate","ice",...
    "identify","ignite","illustrate","impart","infect","infrared","infuse",...
    "ingest","inhibit","inspect","intend","intensify","interfere","invert",...
    "irradiate","juiced","kill","lactose","lard","leach","lease","leaven",...
    "license","lighten","link","liquefy","loaf","locate","lump","manufacture",...
    "marble","mark","market","marry","mellow","migrate","mimic","minimize",...
    "moderate","modify","monitor","multiply","observe","occur","often",...
    "open-faced","operate","oppose","organize","outline","overcrowd",...
    "overfill","overheat","overmix","overmixing","overpower","paint",...
    "pair","paper-lined","paste","pastry","pear-shaped","pearl","perceive",...
    "perform","plant","plate","plump","portion","pose","poultry","practice",...
    "prebaked","price","prick","prohibit","pronounce","proof","protein",...
    "pulse","punch","puréed","puréeing","quarter","raisin","ranch",...
    "ranch-raised","range","raspberry","react","reflect","register",...
    "regulate","rehydrated","relax","relish","rely","render","repair",...
    "report","reprint","reproduce","research","restrict","retard","reuse",...
    "revise","ring","ruin","rye","salt-cured","sand","scallop","secure",...
    "share","shellfish","ship","shock","side","single-celled","skilled",...
    "slaughter","slope","slow","smell","smooth","soft-cooked","solidify",...
    "sophisticate","sound","sour","specify","speed","spell","spice","spill",...
    "splash","spoil","spray","stabilize","stale","stamp","standardize",...
    "starch","state","step","stiff","stimulate","stir-fried","strain",...
    "strike","stripe","study","subject","submerge","suckle","sucrose",...
    "suffer","sugar","sun-dried","supervise","survive","suspend","sweat",...
    "syrup","tap","tart","temperature","thread","thrive","tout","trace",...
    "train","transmit","transport","trap","undercooked","unmold","unsalted",...
    "unsweetened","vitamin","waste","wear","web-based","weigh","whereas",...
    "whole-wheat","wrinkle","yeast"];

bag2=removeWords(bag,exclude_not_actions);
bag2=removeWords(bag2,exclude_process);
bag2=removeWords(bag2,exclude_purposes);
bag2=removeWords(bag2,exclude_others);
bag2=removeWords(bag2,exclude_errors);
bag2=removeWords(bag2,exclude_more);

tmp = table(bag2.Vocabulary','VariableNames',{book});
eval(['selected_verbs_' book '= sortrows(tmp,book,''ascend'');']);












